services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dialog-backend
    environment:
      - NODE_ENV=production
      - PORT=8081 #it was 8081 since before
      - CORS_ORIGIN=http://localhost:5173
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_TIMEOUT_MS=30000

      # OpenTelemetry
      - OTEL_SERVICE_NAME=dialog-backend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
    ports:
      - "8081:8081"
    depends_on:
      - jaeger
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dialog-frontend
    ports:
      - "5173:80"   # host:5173 -> container:80 (nginx)
    depends_on:
      - backend
    restart: unless-stopped
